Translating Mobile and hello p5.js examples part 5
SanjaySinghRajpoot/p5.js-website pull request #13
Opened 2021-06-27 15:48 UTC by SanjaySinghRajpoot

An outcome of Google Summer of Code 2021
Author- Sanjay Singh Rajpoot @SanjaySinghRajpoot
Mentor - Aditya Rana @ranaaditya

2021-07-04 17:31 UTC, ranaaditya requested changes

2021-07-04 17:31 UTC, ranaaditya commented on src/data/examples/hi/35_Mobile/01_Simple_Draw.js
> +  * @description माउसX, mouseY, pmouseX, और pmouseY मानों का उपयोग करके स्क्रीन पर ड्रा करने के लिए स्पर्श करें।
Don't translate processing references into hindi

2021-07-12 04:29 UTC, SanjaySinghRajpoot reviewed
keyword changed

2021-07-12 04:29 UTC, SanjaySinghRajpoot commented on src/data/examples/hi/35_Mobile/01_Simple_Draw.js
> +  * @description माउसX, mouseY, pmouseX, और pmouseY मानों का उपयोग करके स्क्रीन पर ड्रा करने के लिए स्पर्श करें।
ok

2021-07-19 08:16 UTC, merged